### ISSUE TITLE
PasswordList Formating

### ISSUE THREAD

**Issue by HurricanKai** [RLEXBuilding/Controller#11]
**Description:**
Have a look at this:
![image](https://user-images.githubusercontent.com/22711887/34259686-8108b0ba-e663-11e7-8d5e-47908538ac4d.png)
**Reproduction:**
Just check some password
Only seems to occure with Good Passwords (not in lists)

**Comment by RLEXBuilding** [comment]
Thank you, it's on our todo list.

**Comment by RLEXBuilding** [comment]
Fixed
