### ISSUE TITLE
CommandList efficency

### ISSUE THREAD

**Issue by HurricanKai** [RLEXBuilding/Controller#12]
**Description:**
You first shoud check the password youll check next for the same lenght,
you may also want to add an "on list with other capitals".

this isnt an bug.

**Comment by RLEXBuilding** [comment]
Thank you, for reporting this issue. This issue is on our todo list 👍

**Comment by RLEXBuilding** [comment]
That's right, but we have password lists, and we iterate throught these lists. We can't filter lenght and capitals.
